---
- name: "Apache installtion using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: Install package
      package: '{{ package }}'
      state: present
      when: ansible_distribution == "centOS"
      loop:
        - epel-release
        - wget
        - git
    - name: Install python-pip
      yum: name=python-pip state=present update_cache=yes
    - name: Install docker python
      pip: name=docker-py
  tasks:
    - name: Download website
      template:
        src: index.html.j2
        dest: /home/admin/index.html
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volume:
          - /home/admin/index.html:/usr/local/apache2/htdoc
      
